language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  app: eve-tools-auth
  api_key:
    secure: KVCcJh+rfuRiPmOZymDimuOPdX3iPNm1Jgotu0maVmC/FeuV65jG3AgNZikqpzlUGJM0mkmtQH+o3+5L7Side0vlaBe3Ou5M1Y2KOFoumMXF/8Jdchx9a5+rd0HMg37Tr7HlZYrw9KQLqpoychVNxWnT9OqmgNLvKhHEawtx6t/53bYDSeTT4sZDPPZANgNLPFefVZk96jFZ3luakmilGO1OGWdP6XtmBUWDwuJuefKM0gWyXhrmPrQJEQD41mB6tvxaNEsRqGwBiWnRxB+t5zcEukDi2kr114Y2qxTcnHnXIvsR/yTkqkdNqZONU+UUh6ziUz00ZIYYNcDDhWZo221U1ii0b3bUb8mbuGb9wwtSe1B1MqF3ruwq67tS9P1hh8c9rEgiD3OU7bpnlB6xp1dorWmkMROG0qxBnPNVN4x5V0DAlPON8bhKSHLSY9vGM6hfhZvT5JtbOFaG/nzvdV3oK6H+ez8B8LMEb94anVeknUqaBOaqufjmcij4WshcP6JdbnJ6XhfSuD+yTFwebPjkOtiS2S++Z+cmlUQ/pPR6wCa79YV3H2kbZ7WlFNOqKQCgM/vyKDn0+equEl9BvkzBOKNrGBZLmOh6kPyE8B/a431Yr7OSyQbq6v/A4dxvWVrAVzV/gqVEnpBgXiAERuxE7jmx5sCPGH5c0ZXrRwY=
